version: "3"

services:
  app:
    build:
      context: ./innotter
    ports:
      - "5000:5000"
    volumes:
      - ./innotter:/app
      - /innotter/node_modules
    networks:
      - innotter
networks:
  innotter:
    external: true